project:
  type: website

website:
  title: "Prueba Técnica | Daniel F. Villa R."
  navbar:
    left:
      - href: PARTE_1.qmd
        text: 'Parte 1'
      - href: PARTE_2.qmd
        text: 'Parte 2'
      - href: PARTE_3.qmd
        text: 'Parte 3'
    right:
      - icon: github
        href: https://github.com/dvillaunal/PRUEBA_TECNICA_INVAMER.git
      - icon: linkedin
        href: https://www.linkedin.com/in/daniel-felipe-villa-rengifo-11b33b20a

format:
  html:
    theme:
      - zephyr
    css: styles.css
    toc: true
    toc-title: "índice"
    code-fold: true
    df-print: paged
    fig-align: center
    link-external-newwindow: true



